directories:
  output: release
  buildResources: build
appId: com.algartempo.programa
productName: ALGARTEMPO FORNECEDORES
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: build/exeicon.ico
  artifactName: ALGARTEMPO-FORNECEDORES-Setup-${version}.exe
  legalTrademarks: ALGARTEMPO FORNECEDORES
  publish:
    - provider: generic
      url: https://algartempo.pt/updates/fornecedores/
  signAndEditExecutable: false
nsis:
  oneClick: false
  perMachine: false
  allowElevation: true
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: ALGARTEMPO FORNECEDORES
  uninstallDisplayName: ALGARTEMPO FORNECEDORES
  installerIcon: build/exeicon.ico
  uninstallerIcon: build/exeicon.ico
  installerHeaderIcon: build/exeicon.ico
  displayLanguageSelector: true
  artifactName: ALGARTEMPO-FORNECEDORES-Setup-${version}.exe
publish:
  - provider: generic
    url: https://algartempo.pt/updates/
electronVersion: 42.1.0
